# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jquery_corpus}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tse-Ching Ho"]
  s.date = %q{2010-03-10}
  s.description = %q{This gem will collect useful and popular jqeury plugins and provide a reliable way to manage it via rails 3 generator.}
  s.email = %q{tsechingho@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/jquery_corpus.feature",
     "features/step_definitions/jquery_corpus_steps.rb",
     "features/support/env.rb",
     "jquery_corpus.gemspec",
     "lib/generators/jquery.rb",
     "lib/generators/jquery/colorbox/USAGE",
     "lib/generators/jquery/colorbox/colorbox_generator.rb",
     "lib/generators/jquery/ui/USAGE",
     "lib/generators/jquery/ui/templates/application.html.erb",
     "lib/generators/jquery/ui/templates/jquery.rb",
     "lib/generators/jquery/ui/ui_generator.rb",
     "lib/jquery_corpus.rb",
     "spec/generators/colorbox_generator_spec.rb",
     "spec/generators/ui_generator_spec.rb",
     "spec/jquery_corpus_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tsechingho/jquery_corpus}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Manage jQuery and it's plugins for Rails 3 applications.}
  s.test_files = [
    "spec/generators/colorbox_generator_spec.rb",
     "spec/generators/ui_generator_spec.rb",
     "spec/jquery_corpus_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.3"])
      s.add_development_dependency(%q<cucumber>, [">= 0.6.3"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.3"])
      s.add_dependency(%q<cucumber>, [">= 0.6.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.3"])
    s.add_dependency(%q<cucumber>, [">= 0.6.3"])
  end
end

